# Generated by Django 4.2.4 on 2023-09-21 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alarm_num', models.CharField(max_length=10)),
                ('alarm_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='L1_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l1_name', models.CharField(max_length=10, unique=True)),
                ('machine_name', models.CharField(max_length=20)),
                ('machine_type', models.CharField(max_length=10)),
                ('machine_image', models.FileField(blank=True, upload_to='')),
                ('machine_status', models.CharField(blank=True, choices=[('01', '正常'), ('02', '修理中/稼働可能'), ('03', '修理中/稼働不可')], max_length=20)),
                ('created_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_id_l1_name', to=settings.AUTH_USER_MODEL)),
                ('updated_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_id_l1_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Issue_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(blank=True, choices=[('01', '機械不具合'), ('02', '電気不具合'), ('03', 'システム不具合'), ('04', '加工精度不良')], max_length=20)),
                ('issue_title', models.TextField()),
                ('issue_detail', models.TextField()),
                ('issue_treatment', models.TextField()),
                ('issue_freeinput', models.TextField()),
                ('issue_datetime', models.DateTimeField(auto_now=True)),
                ('issue_fixparts', models.CharField(max_length=20)),
                ('issue_fixdate', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_quotation', models.FileField(blank=True, upload_to='')),
                ('file_report', models.FileField(blank=True, upload_to='')),
                ('file_image1', models.FileField(blank=True, upload_to='')),
                ('file_image2', models.FileField(blank=True, upload_to='')),
                ('alarm_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_nums_issue', to='mc_report.alarm')),
                ('created_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_l1_name_issue', to=settings.AUTH_USER_MODEL)),
                ('l1_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='l1_name_issue', to='mc_report.l1_name')),
                ('updated_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updated_l1_name_issue', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
