# Generated by Django 4.2.4 on 2023-08-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=10),
        ),
    ]
