# Generated by Django 4.2.4 on 2023-08-18 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l1_name',
            name='l1_name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
