# Generated by Django 4.2.4 on 2023-08-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='l1_name',
            name='machine_status',
            field=models.CharField(blank=True, choices=[('01', '正常'), ('02', '修理中')], max_length=20),
        ),
    ]
