# Generated by Django 4.2.4 on 2023-08-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_report', '0002_l1_name_machine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='l1_name',
            name='machine_status',
            field=models.CharField(blank=True, choices=[('01', '正常'), ('02', '修理中/稼働可能'), ('03', '修理中/稼働不可')], max_length=20),
        ),
    ]
