# Generated by Django 4.2.4 on 2023-08-18 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_report', '0003_alter_l1_name_machine_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_history',
            name='file_image1',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='issue_history',
            name='file_image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='issue_history',
            name='file_quotation',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='issue_history',
            name='file_report',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
