# Generated by Django 4.2.4 on 2023-08-08 08:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mc_report', '0004_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlarmNum', models.CharField(max_length=10)),
                ('AlarmName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Issue_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L1_Name', models.CharField(max_length=10)),
                ('AlarmNum', models.CharField(max_length=10)),
                ('IssueType', models.TextField()),
                ('IssueTitle', models.TextField()),
                ('IssueDetail', models.TextField()),
                ('IssueDatetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('CreatedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('UpdatetedAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('UserId', models.CharField(max_length=5)),
                ('UpdatedId', models.CharField(max_length=5)),
                ('File_Quotation', models.FileField(upload_to='')),
                ('File_Report', models.FileField(upload_to='')),
                ('File_Image1', models.FileField(upload_to='')),
                ('File_Image2', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='L1_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('L1_Name', models.CharField(max_length=10)),
                ('MachineName', models.CharField(max_length=20)),
                ('MachineType', models.CharField(max_length=10)),
                ('CreatedId', models.CharField(max_length=5)),
                ('UpdatedId', models.CharField(max_length=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
