# Generated by Django 4.2.4 on 2023-08-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mc_report', '0004_alter_issue_history_file_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='l1_name',
            name='machine_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
