# Generated by Django 4.2.4 on 2023-09-15 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=12, unique=True, verbose_name='従業員番号'),
        ),
    ]
